In [1]:
import pandas as pd
import numpy as np

pd.options.plotting.backend = "plotly"

In [2]:
hourly_data_path = 'students_drahi_production_consumption_hourly_completed.csv'
hourly_data = pd.read_csv(hourly_data_path)

hourly_data

datetime  AirTemp      pres   rain      rh       wd  \
0      2022-01-01 00:00:00+00:00   10.279  1005.058  0.000  95.870  187.576   
1      2022-01-01 01:00:00+00:00   10.318  1004.790  0.000  95.335  218.280   
2      2022-01-01 02:00:00+00:00    9.901  1004.791  0.013  95.699  185.351   
3      2022-01-01 03:00:00+00:00    9.444  1004.554  0.000  95.881  193.537   
4      2022-01-01 04:00:00+00:00    8.587  1004.524  0.000  96.738  174.806   
...                          ...      ...       ...    ...     ...      ...   
17515  2023-12-31 19:00:00+00:00    7.523   983.610  0.000  77.079  248.157   
17516  2023-12-31 20:00:00+00:00    7.021   984.488  0.000  81.753  246.199   
17517  2023-12-31 21:00:00+00:00    6.746   984.980  0.000  83.942  245.813   
17518  2023-12-31 22:00:00+00:00    6.703   985.161  0.000  83.873  241.623   
17519  2023-12-31 23:00:00+00:00    6.574   985.901  0.000  82.309  251.971   

          ws  Global_Solar_Flux  Diffuse_Solar_Flux  Direct_Solar_Flux  ...  \
0      1.758             -0.271              -0.370             -0.110  ...   
1      2.401             -0.371              -0.499             -0.231  ...   
2      1.821             -0.846              -0.999             -0.235  ...   
3      1.760             -0.632              -0.755             -0.173  ...   
4      1.613             -0.395              -0.489             -0.110  ...   
...      ...                ...                 ...                ...  ...   
17515  5.871             -1.114              -1.283             -0.246  ...   
17516  5.223             -1.130              -1.270              0.178  ...   
17517  4.572             -0.944              -1.041              0.281  ...   
17518  4.568             -0.935              -1.029              0.203  ...   
17519  4.799             -1.157              -1.273              0.051  ...   

       kw_heatingcoolingtotal_zone1  kw_heatingcoolingtotal_zone2  \
0                            -1.798                        -2.037   
1                            -1.794                        -2.170   
2                            -1.795                        -2.202   
3                            -1.811                        -2.238   
4                            -1.814                        -2.287   
...                             ...                           ...   
17515                        -1.058                        -1.896   
17516                        -1.070                        -1.886   
17517                        -7.507                        -1.890   
17518                        -3.758                        -1.868   
17519                        -3.758                        -1.868   

       kw_lights_zone1  kw_lights_zone2  kw_total_zone1  kw_total_zone2  \
0               -0.002           -0.222           2.091           2.308   
1               -0.002           -0.278           2.086           2.504   
2               -0.002           -0.238           2.085           2.501   
3               -0.002           -0.240           2.100           2.539   
4               -0.002           -0.280           2.102           2.952   
...                ...              ...             ...             ...   
17515           -0.130           -0.031           1.659           2.058   
17516           -0.121           -0.019           1.661           2.038   
17517           -0.120           -0.019           8.045           2.049   
17518           -0.120           -0.019           4.361           2.021   
17519           -0.120           -0.019           4.361           2.021   

       kw_ventilation_zone1  kw_ventilation_zone2  kw_water_heater_zone2  \
0                    -0.027                -0.030                 -0.004   
1                    -0.027                -0.044                 -0.004   
2                    -0.026                -0.043                 -0.004   
3                    -0.026                -0.044                 -0.004   
4               

In [3]:
hourly_data_index = hourly_data.set_index("datetime")

hourly_data_index

AirTemp      pres   rain      rh       wd     ws  \
datetime                                                                      
2022-01-01 00:00:00+00:00   10.279  1005.058  0.000  95.870  187.576  1.758   
2022-01-01 01:00:00+00:00   10.318  1004.790  0.000  95.335  218.280  2.401   
2022-01-01 02:00:00+00:00    9.901  1004.791  0.013  95.699  185.351  1.821   
2022-01-01 03:00:00+00:00    9.444  1004.554  0.000  95.881  193.537  1.760   
2022-01-01 04:00:00+00:00    8.587  1004.524  0.000  96.738  174.806  1.613   
...                            ...       ...    ...     ...      ...    ...   
2023-12-31 19:00:00+00:00    7.523   983.610  0.000  77.079  248.157  5.871   
2023-12-31 20:00:00+00:00    7.021   984.488  0.000  81.753  246.199  5.223   
2023-12-31 21:00:00+00:00    6.746   984.980  0.000  83.942  245.813  4.572   
2023-12-31 22:00:00+00:00    6.703   985.161  0.000  83.873  241.623  4.568   
2023-12-31 23:00:00+00:00    6.574   985.901  0.000  82.309  251.971  4.799   

                           Global_Solar_Flux  Diffuse_Solar_Flux  \
datetime                                                           
2022-01-01 00:00:00+00:00             -0.271              -0.370   
2022-01-01 01:00:00+00:00             -0.371              -0.499   
2022-01-01 02:00:00+00:00             -0.846              -0.999   
2022-01-01 03:00:00+00:00             -0.632              -0.755   
2022-01-01 04:00:00+00:00             -0.395              -0.489   
...                                      ...                 ...   
2023-12-31 19:00:00+00:00             -1.114              -1.283   
2023-12-31 20:00:00+00:00             -1.130              -1.270   
2023-12-31 21:00:00+00:00             -0.944              -1.041   
2023-12-31 22:00:00+00:00             -0.935              -1.029   
2023-12-31 23:00:00+00:00             -1.157              -1.273   

                           Direct_Solar_Flux  Downwelling_IR_Flux  ...  \
datetime                                                           ...   
2022-01-01 00:00:00+00:00             -0.110              342.922  ...   
2022-01-01 01:00:00+00:00             -0.231              328.399  ...   
2022-01-01 02:00:00+00:00             -0.235              288.659  ...   
2022-01-01 03:00:00+00:00             -0.173              309.317  ...   
2022-01-01 04:00:00+00:00             -0.110              323.557  ...   
...                                      ...                  ...  ...   
2023-12-31 19:00:00+00:00             -0.246              259.846  ...   
2023-12-31 20:00:00+00:00              0.178              261.117  ...   
2023-12-31 21:00:00+00:00              0.281              289.698  ...   
2023-12-31 22:00:00+00:00              0.203              279.778  ...   
2023-12-31 23:00:00+00:00              0.051              258.689  ...   

                           kw_heatingcoolingtotal_zone1  \
datetime                                                  
2022-01-01 00:00:00+00:00                        -1.798   
2022-01-01 01:00:00+00:00                        -1.794   
2022-01-01 02:00:00+00:00                        -1.795   
2022-01-01 03:00:00+00:00                        -1.811   
2022-01-01 04:00:00+00:00                        -1.814   
...                                                 ...   
2023-12-31 19:00:00+00:00                        -1.058   
2023-12-31 20:00:00+00:00                        -1.070   
2023-12-31 21:00:00+00:00                        -7.507   
2023-12-31 22:00:00+00:00                        -3.758   
2023-12-31 23:00:00+00:00                        -3.758   

                           kw_heatingcoolingtotal_zone2  kw_lights_zone1  \
datetime                                                                   
2022-01-01 00:00:00+00:00                        -2.037           -0.002   
2022-01-01 01:00:00+00:00                        -2.170           -0.002   
2022-01-01 02:00:00+00:00                        -2.202           -0.002   
202

In [4]:
from sklearn.preprocessing import FunctionTransformer

#Little hack to "freeze" transformers, since the data in the input is flattened 

def fit_and_freeze(transformer):
    fitted = [0]

    def func(x):
        if not fitted[0]:
            transformer.fit(x)
            fitted[0] = 1
        return transformer.transform(x)

    return FunctionTransformer(func)

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

pipe = Pipeline([('scaler', fit_and_freeze(StandardScaler()))])
pipe.fit(hourly_data_index["AirTemp"].values.reshape(-1, 1))

Pipeline(steps=[('scaler',
                 FunctionTransformer(func=<function fit_and_freeze.<locals>.func at 0x000001C45F103CE0>))])

In [6]:
pipe.transform(hourly_data_index["AirTemp"].values.reshape(-1, 1))

array([[-0.39608824],
       [-0.39061989],
       [-0.44908921],
       ...,
       [-0.89146503],
       [-0.89749424],
       [-0.91558187]])

In [7]:
hourly_data_index["AirTemp"]

datetime
2022-01-01 00:00:00+00:00    10.279
2022-01-01 01:00:00+00:00    10.318
2022-01-01 02:00:00+00:00     9.901
2022-01-01 03:00:00+00:00     9.444
2022-01-01 04:00:00+00:00     8.587
                              ...  
2023-12-31 19:00:00+00:00     7.523
2023-12-31 20:00:00+00:00     7.021
2023-12-31 21:00:00+00:00     6.746
2023-12-31 22:00:00+00:00     6.703
2023-12-31 23:00:00+00:00     6.574
Name: AirTemp, Length: 17520, dtype: float64

In [8]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(transformers=[
    ('AirTemp', pipe, ["AirTemp"]),
    #('Other', 'passthrough', ["rain"])
])

preprocessor.fit_transform(hourly_data_index)

C:\Users\Concordance\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


array([[-0.39608824],
       [-0.39061989],
       [-0.44908921],
       ...,
       [-0.89146503],
       [-0.89749424],
       [-0.91558187]])

In [9]:
from sklearn.preprocessing import StandardScaler

scaler_air_temp = StandardScaler()

scaler_air_temp.fit(hourly_data_index["AirTemp"].values.reshape(1, -1))
scaler_air_temp.transform(hourly_data_index["AirTemp"].values.reshape(1, -1))

#pd.DataFrame(StandardScaler().fit_transform(hourly_data_index["AirTemp"].values.reshape(-1, 1))).hist()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [10]:
time = pd.to_datetime(hourly_data['datetime']).values.astype('datetime64[s]')
power_consumption = hourly_data['kw_total_zone2'].values

dec = [] # daily energy consumption
t_dec = []

for ti, t in enumerate(time):
    tmp_t = pd.Timestamp(t)

    if np.isclose(tmp_t.hour, 0) and np.isclose(tmp_t.minute, 0):

        day_end = np.datetime64(tmp_t + pd.Timedelta(days=1))
        ind = np.where((time > tmp_t) & (time < day_end), True, False)

        if len(time[ind]) > 0 and not np.isnan(power_consumption[ind]).any():
            t_dec.append(np.datetime64(tmp_t).astype('datetime64[s]'))
            dec.append(np.trapz(power_consumption[ind], time[ind].astype(int))/3600)

t_dec = np.array(t_dec)
dec = np.array(dec)

In [ ]:
N = 7 # N days of predictors beforehand
final_ind = []
final_hourly = []

predictor_window = pd.Timedelta(days=N)

for ti, t in enumerate(t_dec):
    tmp_t = pd.Timestamp(t)

    ind = np.where((time >= tmp_t - predictor_window) & (time < tmp_t), True, False) # finding indices within the N prior days

    bad_ind = np.isnan(hourly_data.iloc[ind, 1::].values)
    if len(time[ind]) >= 24 * N and not bad_ind.any(): # rejecting any data with NaNs; useful for the student dataset
        final_ind.append(ti)
        final_hourly.append(hourly_data.iloc[ind, 1::].values)

target_time = t_dec[final_ind]
predictors = np.array(final_hourly)

X = pd.DataFrame(predictors.reshape(len(predictors), -1))
y = pd.DataFrame(np.array(dec[final_ind]))

In [ ]:

from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=148)

#reg = Ridge(alpha=1e8)
#reg.fit(x_train, y_train)
#y_pred = reg.predict(x_test)

In [ ]:
X

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import FunctionTransformer

# preprocessor = Pipeline(steps=[])

model = Pipeline(steps=[
    # ('preprocessor', preprocessor),
    # ('classifier', Ridge(alpha=1e8))
    ('regressor', GradientBoostingRegressor(verbose=True)),
])

model.fit(X_train, y_train.values.ravel())

In [ ]:
from skimage.metrics import mean_squared_error
from sklearn.model_selection import cross_validate

-mean_squared_error(y_test.values.ravel(), model.predict(X_test))
#np.mean(cross_validate(model, X, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')['test_score'])

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {} # {'alpha': np.logspace(-2, 20, 21)}

grid = GridSearchCV(GradientBoostingRegressor(), param_grid, cv=5, scoring='neg_mean_squared_error')

grid.fit(X, y) # using the entire dataset for validation

best_alpha = grid.best_params_['alpha']
best_rse = -grid.best_score_/np.mean((y-y.mean())**2)
print('Best alpha from validation:', best_alpha)

In [ ]:
best_model = grid.best_estimator_
np.mean(cross_validate(best_model, X, y, cv=10, scoring='neg_mean_squared_error')['test_score'])

In [ ]:
def relative_squared_error(y_pred, y_true):
    """Relative squared error (RSE; also called relative mean square error). < 1 is good, = 1 is bad, > 1 really bad."""
    return np.mean((y_pred - y_true)**2)/np.mean((y_true - y_true.mean())**2)

relative_squared_error(model.predict(X), y.values.ravel())

In [ ]:
model.predict(X).reshape(-1,1).shape

In [ ]:
wrapper = Pipeline([('wrapper', FunctionTransformer(lambda X: model.predict(X).reshape(-1,1)))])

In [ ]:
model.predict(X)

In [ ]:
model.predict(X)

In [ ]:
X.shape